name: Deploy package to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:

  build-linux:
    name: Build Linux wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "musllinux_1_2_armv7l"
        folder:
          - "cp312-cp312"

    steps:
      - uses: actions/checkout@v4

      - name: Update version in pyproject.toml from current git tag
        run: |
          sed -i "s/0\\.0\\.0\\.dev0/${GITHUB_REF_NAME/v/}/g" pyproject.toml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,arm

      - name: Build packages
        run: >-
          docker run --rm -v ${{ github.workspace }}:/app quay.io/pypa/${{ matrix.image }} bash -c '
            apt-get install arm-linux-musleabihf-gcc &&
            cd /app &&
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
            . "$HOME/.cargo/env" &&
            /opt/python/${{ matrix.folder }}/bin/python -m build --wheel
            auditwheel repair $(ls dist/*.whl) &&
            rm dist/*.whl &&
            cp wheelhouse/*.whl dist
          '
